"""initial

Revision ID: fbf83c006d69
Revises: 14a162c8132a
Create Date: 2024-08-12 20:22:51.675027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbf83c006d69'
down_revision: Union[str, None] = '14a162c8132a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_flower_name', table_name='flower')
    op.drop_index('ix_user_username', table_name='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.create_index('ix_flower_name', 'flower', ['name'], unique=False)
    # ### end Alembic commands ###
